### ISSUE TITLE
Can't access disabled entries

### ISSUE THREAD

**Issue by diluno** [craftcms/element-api#104]
I'm having some trouble accessing disabled entries.
I have two sites (DE and FR), and call the API by their respective site-URL. (/api/entries or /fr/api/entries).
I would like to get the entries for each site whether they're disabled or not.

I tried the following critierias, and always got a 404:

`'criteria' => ['enabledForSite' => false, 'slug' => $slug]`
`'criteria' => ['anyStatus' => true, 'slug' => $slug]`
`'criteria' => ['status' => ['disabled', 'live'], 'slug' => $slug]`

**Comment by elodiegrondin** [comment]
Hi @diluno Did you find any solution for this ?

**Comment by diluno** [comment]
No, unfortunately I didn't.

**Comment by ryanpcmcquen** [comment]
@diluno, where did you get that list of `status` types? If I combine that with `'draftId' => $draftId,` then I can get a disabled entry. But I want to make sure I'm not missing any `status` types.

**Comment by diluno** [comment]
I tried getting all entries, with status "disabled" or "live".
I think getting one specific disabled entry works (with 'draftId'), but I can't seem to get multiple.

**Comment by ryanpcmcquen** [comment]
@diluno, are there other statuses besides 'disabled' and 'live'?

**Comment by diluno** [comment]
> @diluno, are there other statuses besides 'disabled' and 'live'?

@ryanpcmcquen Yes, there are the following statuses:
'live', 'pending', 'expired', 'disabled'

**Comment by ryanpcmcquen** [comment]
@diluno, where are these documented?

**Comment by diluno** [comment]
Here: https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#status

**Comment by olivierbon** [comment]
Wether entries are 'live', 'pending', 'expired' or 'disabled', adding `'status' => null` to your criteria will:

- Return them all in case of a listing
- Return the entry (no 404) in case of a single entry

**Comment by diluno** [comment]
Unfortunately this doesn't work if I disable it just for one site, and then try getting all entries for that site.
For example I have a site in German and one in French. If I disable an entry only for the French site, it doesn't show up in /fr/api/entries, even with `'status' => null`.
It only works by disabling it globally.
