### ISSUE TITLE
get element by URI

### ISSUE THREAD

**Issue by oddnavy** [craftcms/element-api#107]
It is possible to define an element-api endpoint which can retrieve an element by URI and handle nested URIs. 

For example, we have an entry with the URI of `/about/our-team` and would like to make an element-api query to `api/pages/about/our-team` or a variation of that. `api/products/<uri>` doesn't seem to work (I'm assuming the regex doesn't match the nested path).

**Comment by brandonkelly** [comment]
Yes, you can do this:

```php
'api/<uri:.*>' => function(string $uri) {
    return [
        'elementType' => craft\elements\Entry::class,
        'criteria' => [
            'uri' => $uri,
        ],
        'one' => true,
    ];
},
```
