### ISSUE TITLE
Control Panel is rendered in plain HTML after activating Element API

### ISSUE THREAD

**Issue by marcwieland95** [craftcms/element-api#110]
Hey,

I'm not sure if this problem just occurs for me or if anyone else also came along this issue.

I just installed a fresh Craft CMS instance, which means it's up to date. Then I installed the plugin to generate JSON endpoints. After composer finishes the install of the Element API plugin my control panel is gone and the plain HTML is outputted on the screen. Which is very strange.

Does anyone have the same issue or know how to solve it?

Thanks and cheers
Marc

**Comment by brandonkelly** [comment]
Guessing you have a syntax error in `config/element-api.php`. Try clearing out your `storage/logs/` folder, then refreshing the CP, and see if anything gets logged (likely in `phperrors.log`).

**Comment by marcwieland95** [comment]
I'll try that out.

Funny thing is that the endpoint itself is working

**Comment by marcwieland95** [comment]
Indeed, I had something inside which seemed to break everything. Not a syntax error but a Craft helper function which broke somehow.

```
Craft::$app->getResponse()->getHeaders()->set('Content-Type', 'Access-Control-Allow-Headers');
```
