### ISSUE TITLE
Logging Element API errors

### ISSUE THREAD

**Issue by oddnavy** [craftcms/element-api#117]
Is there a way to log exceptions caught in the element-api actionIndex? The code looks like it catches exceptions thrown.

https://github.com/craftcms/element-api/blob/v2/src/controllers/DefaultController.php#L165

For context, we want to log exceptions that cause 500s in my element-api to Rollbar.

Current code to log exceptions:

```php
Event::on(
  ErrorHandler::class,
  ErrorHandler::EVENT_BEFORE_HANDLE_EXCEPTION,
  function (ExceptionEvent $event) {
    Rollbar::error($event->exception);
  }
);
```

**Comment by yoannisj** [comment]
@oddnavy if the controller logs thrown exceptions (I just opened a [PR](https://github.com/craftcms/element-api/pull/139) to add logging), I believe you should be able to send all errors by adding a [log target](https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging#log-targets) in your project's `config/app.php` file.

**Comment by brandonkelly** [comment]
Element API 2.7.0 is out now with this change.
