### ISSUE TITLE
Optionally ignore exceptions for queries that return empty

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/element-api#118]
Sometimes, especially on requests using search queries, we don't want exceptions to be thrown when the query returns empty. Could we have an option to not throw these?

**Comment by brandonkelly** [comment]
The only time I’m seeing an error returned for an entry result are when `one` is used. You can avoid that by not including `'one' => true`in your endpoint config, and instead setting `'limit' => 1` in your criteria.
