### ISSUE TITLE
404

### ISSUE THREAD

**Issue by AshtonKem** [craftcms/element-api#121]
It does not appear like this plugin is working with CraftCMS 3.3.X, as I am only getting a 404 when requesting this API.

element-api.php
```
<?php
use craft\elements\Entry;
use craft\helpers\UrlHelper;

return [
    'endpoints' => [
        'api/articles.json' => function() {
            return [
                'elementType' => Entry::class,
                'criteria' => ['section' => 'articles'],
                'transformer' => function(Entry $entry) {
                    return [
                        'title' => $entry->title,
                        'url' => $entry->url
                    ];
                },
            ];
        },
    ]
];
```

**Comment by AshtonKem** [comment]
I figured it out, it looks like having `.json` at the end of the endpoint causes the 404. Changing the above to `api/articles` fixes it.

**Comment by ul8** [comment]
I am getting the same issue - previously working API endpoints do no longer work after updating to 3.3.x

@AshtonKem are you sure about your fix, is that really the only thing you changed? It seems very odd that the ".json" should have any negative impact. I tried the same but that didn't fix it.

**Comment by AshtonKem** [comment]
That is the only thing I changed, and it fixed the issue for me.

**Comment by bertheyman** [comment]
Can confirm this bug.
Working with element api 2.6.0 and Craft 3.4.17.
Endpoint returns 404 (with or without .json).

@brandonkelly, do you have a fix you can recommend?

**Comment by ul8** [comment]
@bertheyman I don't remember what exactly it was, but for me this issue was ultimately caused by some custom module or other plugin code. I recommend you disable all plugins and modules and see if that helps to isolate it.

**Comment by bertheyman** [comment]
@ul8 Indeed, was an overlooked issue on our side. Thanks!
@AshtonKem Did you get to solve your problem? Can the issue be closed?

**Comment by AshtonKem** [comment]
I no longer work at the company where I had this issue, so I don’t have the source necessary to reproduce. 

—
Ashton Kemerling

**Comment by rsryanstephen** [comment]
Getting the same error.

<?php

use craft\elements\Entry;
use craft\elements\User;

return [
    'endpoints' => [
        'blogAuthors/<blogUri>.json' => function ($blogUri) {
            return [
                'elementType' => Entry::class,
                'criteria' => ['uri' => $blogUri],
                'one' => true,
                'includes' => (array)Craft::$app->request->getQueryParam('include'),
                'transformer' => function (Entry $entry) {
                    return $this->item($entry->author, function (User $author) {
                        return [
                            'username' => $author->username,
                            'email' => $author->email
                        ];
                    });
                },
            ];
        },
    ]
];
