### ISSUE TITLE
[Question] Where is the cache stored?

### ISSUE THREAD

**Issue by brianjhanson** [craftcms/element-api#122]
I've been digging around for the last few days trying to find exactly where the cache for the element-api is stored. We implemented a cache clearing solution [as suggested by Brad](https://github.com/craftcms/element-api/issues/55#issuecomment-321029873) but that doesn't seem to clear the entire cache. I haven't had much success clearing the cache unless I clear _everything_ but I was curious if there was a more targeted solution. 

Thanks!

**Comment by brandonkelly** [comment]
Caches are stored right alongside other data caches. As of Element API 2.7.0, you can clear _just_ the Element API caches via the Caches utility, or the `craft invalidate-tags/element-api` command.
