### ISSUE TITLE
Google tried indexing element api URl

### ISSUE THREAD

**Issue by piotrpog** [craftcms/element-api#124]
I have element API endpoint which requires specific URL attributes to work. 

If I enter directly endpoint URL in the browser, it returns error and error code 500:

```
{"error":{"code":2,"message":"Invalid argument supplied for foreach()"}}
```

This is expected behavior, but for some reason, google search console started including endpoint URL in its report. It didnt indexed that site, but showed error:

```
Server error (5xx)
```

Maybe there should be some additional HTTP header in such situation that would block google?

**Comment by brandonkelly** [comment]
Just released Element API 2.8.0 which sets `X-Robots-Tag: none` headers on all API endpoint responses, so this shouldn’t happen anymore.
