### ISSUE TITLE
Internal links to the entries in redactor field does not render in JSON.

### ISSUE THREAD

**Issue by CodeCurosity** [craftcms/element-api#126]
We have HTML content using redactor field, its gets all the html and external links but internal links to the entries are not rendered and shows this {entry:43135:url}

**Comment by brandonkelly** [comment]
You should be including the Redactor field via:

```php
'body' => (string)$entry->myRedactorField,
```
or
```php
'body' => $entry->myRedactorField->getParsedContent(),
```

If you do either of those, the reference tags will be parsed correctly.
