### ISSUE TITLE
Order results by two fields

### ISSUE THREAD

**Issue by Stalex89** [craftcms/element-api#127]
For example I need to sort out news topics first by top news (boolean), then by post date. So first I should have all top news ordered by post date, then all of the rest topics ordered by post date.
Is it possible to output the results ordered by two fields ? 

Something like that:
```
                'criteria' => [
                    'orderBy' => ['isOnTop' ,'postDate desc']
                ],
```

**Comment by BeKnowDo** [comment]
Did you resolve your issue?

**Comment by MaartenVenema** [comment]
I know this one is closed but if someone comes by this for some reason you can set multiple order commands by seperating them by a `,` so for example `'orderBy' => 'postDate asc, starttime asc'`. Setting them as a array results in errors for me and this seems to work.
