### ISSUE TITLE
Grouping results

### ISSUE THREAD

**Issue by rgbjay** [craftcms/element-api#131]
Probably a simple answer but, how can we return entries grouped by the month they were posted based on the `postDate` field?

I am trying to return an endpoint for a blog archive sidebar in a VueJS app.

Thanks in advance.

**Comment by headerlocation** [comment]
@rgbjay Have you found a solution?

**Comment by mmikhalko** [comment]
I have the same question, I would like to group entries by the category field that is in the entries

**Comment by brandonkelly** [comment]
This isn’t possible, and not something we could add. You would need to apply that grouping on the receiving end of the results.
