### ISSUE TITLE
Profiling and debug toolbar on element API endpoints

### ISSUE THREAD

**Issue by jamealg** [craftcms/element-api#132]
Is there any conceivable way to access the debug toolbar on element API endpoints? I'm wondering if there is a best practice for profiling with element API.

**Comment by jamealg** [comment]
I found out that accessing `/debug` will take you to Yii's debugger and from there it's possible to find logs for requests to Element API endpoints. It's slightly less convenient but it works. If there were an option to return element API endpoints as HTML with the Yii debug toolbar that would be a wonderful feature to make profiling easier.

**Comment by brandonkelly** [comment]
If you’re logged into an account that has the Debug Toolbar enabled for front-end requests, Element API requests will come back with a `X-Debug-Link` header, set to a URL where you can view the debug toolbar report for that request.
