### ISSUE TITLE
Entry Drafts and Versions documentation missing on Tag 2.6

### ISSUE THREAD

**Issue by Mmasson-01** [craftcms/element-api#134]
### Description

Since tag v.2.6 documentation for Entry Drafts and Versions is missing. Nothing in the changelog pointing to a deprecation.

Is it still available and removed by mistake ?

**Comment by Mmasson-01** [comment]
In the deprecation note

**Comment by brandonkelly** [comment]
The old draft/version support has been removed since Craft 3.2+ is capable of returning drafts and revisions via normal entry queries, using `drafts`, `draftId`, `draftOf`, revisions`, `revisionId`, and `revisionOf` params.
