### ISSUE TITLE
Not correct error when use an argument in callback

### ISSUE THREAD

**Issue by mmikhalko** [craftcms/element-api#137]
### Description

If add not use argument to endpoint is returning incorrect response:

{"error":{"code":404,"message":"Endpoint has an invalid elementType"}}

### Steps to reproduce

'api/articles' => function($someId) {
   ..
}

1. Add code 
2. Make a request
3. Check error message of response 
4. 
### Additional info

- Craft version: 3.5.14
- PHP version:  7.3.15
- Database driver & version: MySQL 5.6.39
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Element API 2.8.0 with a fix.
