### ISSUE TITLE
Exception thrown when trying to fetch SproutForms_Entry entries

### ISSUE THREAD

**Issue by ECMichael** [craftcms/element-api#14]
I'm trying to pull back all sprout form entries using the following elementapi.php file;

```

<?php

    namespace Craft;

    return [
        "endpoints" => [
            "comp-results/<sourceEntryId:\d+>" => [
                "elementType" => "SproutForms_Entry"
            ]
        ]
    ];
```

Unfortunately Craft is throwing the following exception;

```
Internal Server Error

CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entries.entries.dateCreated' in 'order clause'
```

Using Craft CMS 2.6.2780, Element API 1.2.1, and Sprout Forms 2.2.5

**Comment by takobell** [comment]
Can you enable devMode, reproduce the error and share the full stack trace?

**Comment by ECMichael** [comment]
`CDbException

CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entries.entries.dateCreated' in 'order clause'. The SQL statement executed was: SELECT `elements`.`id`, `elements`.`type`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_i18n`.`slug`, `elements_i18n`.`uri`, `elements_i18n`.`enabled` AS `localeEnabled`, `entries`.`id`, `entries`.`ipAddress`, `entries`.`userAgent`, `entries`.`dateCreated`, `entries`.`dateUpdated`, `entries`.`uid`, `forms`.`id` AS `formId`, `forms`.`name` AS `formName`, `forms`.`groupId` AS `formGroupId`, `easter2017`.`title`, `easter2017`.`field_yourName` AS `yourName`, `easter2017`.`field_yourEmail` AS `yourEmail`, `easter2017`.`field_childsName` AS `childsName`, `easter2017`.`field_childsAge` AS `childsAge`
FROM `craft_elements` `elements`
JOIN `craft_elements_i18n` `elements_i18n` ON elements_i18n.elementId = elements.id
JOIN `craft_sproutforms_entries` `entries` ON entries.id = elements.id
JOIN `craft_sproutforms_forms` `forms` ON forms.id = entries.formId
JOIN `craft_sproutformscontent_easter2017` `easter2017` ON easter2017.elementId = elements.id
WHERE ((((elements_i18n.locale = :locale) AND (elements.archived = 0)) AND (elements.enabled = 1)) AND (elements_i18n.enabled = 1)) AND (forms.handle=:formshandle1)
GROUP BY `elements`.`id`
ORDER BY `entries`.`entries`.`dateCreated` DESC LIMIT 3. Bound with :locale='en_us', :formshandle1='easter2017'

/var/www/nisalocally.dev/craft/app/framework/db/CDbCommand.php(543)

531         {
532             if($this->_connection->enableProfiling)
533                 Yii::endProfile('system.db.CDbCommand.query('.$this->getText().$par.')','system.db.CDbCommand.query');
534 
535             $errorInfo=$e instanceof PDOException ? $e->errorInfo : null;
536             $message=$e->getMessage();
537             Yii::log(Yii::t('yii','CDbCommand::{method}() failed: {error}. The SQL statement executed was: {sql}.',
538                 array('{method}'=>$method, '{error}'=>$message, '{sql}'=>$this->getText().$par)),CLogger::LEVEL_ERROR,'system.db.CDbCommand');
539 
540             if(YII_DEBUG)
541                 $message.='. The SQL statement executed was: '.$this->getText().$par;
542 
543             throw new CDbException(Yii::t('yii','CDbCommand failed to execute the SQL statement: {error}',
544                 array('{error}'=>$message)),(int)$e->getCode(),$errorInfo);
545         }
546     }
547 
548     /**
549      * Builds a SQL SELECT statement from the given query specification.
550      * @param array $query the query specification in name-value pairs. The following
551      * query options are supported: {@link select}, {@link distinct}, {@link from},
552      * {@link where}, {@link join}, {@link group}, {@link having}, {@link order},
553      * {@link limit}, {@link offset} and {@link union}.
554      * @throws CDbException if "from" key is not present in given query parameter
555      * @return string the SQL statement
Stack Trace
#0	
–  /var/www/nisalocally.dev/craft/app/framework/db/CDbCommand.php(396): CDbCommand->queryInternal("fetchAll", array(2), array())
391      * An empty array is returned if the query results in nothing.
392      * @throws CException execution failed
393      */
394     public function queryAll($fetchAssociative=true,$params=array())
395     {
396         return $this->queryInternal('fetchAll',$fetchAssociative ? $this->_fetchMode : PDO::FETCH_NUM, $params);
397     }
398 
399     /**
400      * Executes the SQL statement and returns the first row of the result.
401      * This is a convenient method of {@link query} when only the first row of data is needed.
#1	
–  /var/www/nisalocally.dev/craft/app/services/ElementsService.php(214): CDbCommand->queryAll()
209         {
210             // Something decided that executing the query is pointless
211             return array();
212         }
213 
214         $results = $query->queryAll();
215 
216         if (!$results)
217         {
218             return array();
219         }
#2	
–  /var/www/nisalocally.dev/craft/app/models/ElementCriteriaModel.php(254): Craft\ElementsService->findElements(Craft\ElementCriteriaModel)
249 
250         $this->_includeInTemplateCaches();
251 
252         if (!isset($this->_matchedElements))
253         {
254             $elements = craft()->elements->findElements($this);
255             $this->setMatchedElements($elements);
256         }
257 
258         return $this->_matchedElements;
259     }
#3	
–  /var/www/nisalocally.dev/craft/plugins/elementapi/controllers/ElementApiController.php(110): Craft\ElementCriteriaModel->find()
105 
106             // Fetch this page's elements
107             $criteria->offset = $config['elementsPerPage'] * ($paginator->getCurrentPage() - 1);
108             $criteria->limit = $config['elementsPerPage'];
109 //$criteria->order = "dateCreated";
110             $elements = $criteria->find();
111             $paginator->setCount(count($elements));
112 
113             $resource = new Collection($elements, $transformer);
114             $resource->setPaginator($paginator);
115         }
#4	
 unknown(0): Craft\ElementApiController->actionGetElements(Closure, null)
#5	
–  /var/www/nisalocally.dev/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Craft\ElementApiController, array(Closure, null))
104             elseif($param->isDefaultValueAvailable())
105                 $ps[]=$param->getDefaultValue();
106             else
107                 return false;
108         }
109         $method->invokeArgs($object,$ps);
110         return true;
111     }
112 }
#6	
–  /var/www/nisalocally.dev/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Craft\ElementApiController, ReflectionMethod, array("p" => "comp-entries/easter-2017", "page" => "1", "variables" => array("matches" => array("comp-entries/easter-2017")), "template" => "comp-entries/easter-2017", ...))
42     {
43         $methodName='action'.$this->getId();
44         $controller=$this->getController();
45         $method=new ReflectionMethod($controller, $methodName);
46         if($method->getNumberOfParameters()>0)
47             return $this->runWithParamsInternal($controller, $method, $params);
48 
49         $controller->$methodName();
50         return true;
51     }
52 }
#7	
–  /var/www/nisalocally.dev/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(array("p" => "comp-entries/easter-2017", "page" => "1", "variables" => array("matches" => array("comp-entries/easter-2017")), "template" => "comp-entries/easter-2017", ...))
303     {
304         $priorAction=$this->_action;
305         $this->_action=$action;
306         if($this->beforeAction($action))
307         {
308             if($action->runWithParams($this->getActionParams())===false)
309                 $this->invalidActionParams($action);
310             else
311                 $this->afterAction($action);
312         }
313         $this->_action=$priorAction;
#8	
–  /var/www/nisalocally.dev/craft/app/framework/web/CController.php(286): CController->runAction(CInlineAction)
281      * @see runAction
282      */
283     public function runActionWithFilters($action,$filters)
284     {
285         if(empty($filters))
286             $this->runAction($action);
287         else
288         {
289             $priorAction=$this->_action;
290             $this->_action=$action;
291             CFilterChain::create($this,$action,$filters)->run();
#9	
–  /var/www/nisalocally.dev/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array())
260         {
261             if(($parent=$this->getModule())===null)
262                 $parent=Yii::app();
263             if($parent->beforeControllerAction($this,$action))
264             {
265                 $this->runActionWithFilters($action,$this->filters());
266                 $parent->afterControllerAction($this,$action);
267             }
268         }
269         else
270             $this->missingAction($actionID);
#10	
–  /var/www/nisalocally.dev/craft/app/framework/web/CWebApplication.php(282): CController->run("getElements")
277         {
278             list($controller,$actionID)=$ca;
279             $oldController=$this->_controller;
280             $this->_controller=$controller;
281             $controller->init();
282             $controller->run($actionID);
283             $this->_controller=$oldController;
284         }
285         else
286             throw new CHttpException(404,Yii::t('yii','Unable to resolve the request "{route}".',
287                 array('{route}'=>$route===''?$this->defaultController:$route)));
#11	
–  /var/www/nisalocally.dev/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController("elementApi/getElements")
136             foreach(array_splice($this->catchAllRequest,1) as $name=>$value)
137                 $_GET[$name]=$value;
138         }
139         else
140             $route=$this->getUrlManager()->parseUrl($this->getRequest());
141         $this->runController($route);
142     }
143 
144     /**
145      * Registers the core application components.
146      * This method overrides the parent implementation by registering additional core components.
#12	
–  /var/www/nisalocally.dev/craft/app/etc/web/WebApp.php(288): CWebApplication->processRequest()
283 
284         // If this is an action request, call the controller
285         $this->_processActionRequest();
286 
287         // If we're still here, finally let UrlManager do it's thing.
288         parent::processRequest();
289     }
290 
291     /**
292      * Returns the target application language.
293      *
#13	
–  /var/www/nisalocally.dev/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
180     public function run()
181     {
182         if($this->hasEventHandler('onBeginRequest'))
183             $this->onBeginRequest(new CEvent($this));
184         register_shutdown_function(array($this,'end'),0,false);
185         $this->processRequest();
186         if($this->hasEventHandler('onEndRequest'))
187             $this->onEndRequest(new CEvent($this));
188     }
189 
190     /**
#14	
–  /var/www/nisalocally.dev/craft/app/index.php(62): CApplication->run()
57 
58 // Load and run Craft
59 // -----------------------------------------------------------------------------
60 
61 $app = require 'bootstrap.php';
62 $app->run();
#15	
–  /var/www/nisalocally.dev/public_html/index.php(14): require_once("/var/www/nisalocally.dev/craft/app/index.php")
09 if (!is_file($path))
10 {
11     exit('Could not find your craft/ folder. Please ensure that <strong><code>$craftPath</code></strong> is set correctly in '.__FILE__);
12 }
13 
14 require_once $path;
2016-05-11 08:23:13 Apache/2.4.7 (Ubuntu) / Craft 2.6.2780`

**Comment by takobell** [comment]
Got a copy of Sprout Forms today... will see if I can reproduce.

**Comment by kmelve** [comment]
I figured it out, `paginate` has to be set to `false` for this to work. For some reasons, an extra `entries` is added to the `ORDER BY` clause in the SQL-query if pagniation is set to true. Potential bug?

```php
<?php
namespace Craft;

return [
    'endpoints' => [
        'api/sproutform.json' => [
            'elementType' => 'SproutForms_Entry',
            'criteria' => ['formId' => 232], /* you can use other criteria as well */
            'paginate' => false, /* this must be set to false */
            'transformer' => function(SproutForms_EntryModel $entry) {
                return [
                    'title' => $entry->title,
                    'slug' => $entry->slug
                ];
            },
        ]
    ]
];
```

**Comment by knynkwl** [comment]
How would this example be formatted in Craft3?

**Comment by angrybrad** [comment]
@knynkwl you can see the Element API 2 syntax here: https://github.com/craftcms/element-api#setup

You'd need to replace whatever the Craft 3 compatible Sprout Forms equivalent class name of  `'SproutForms_Entry'` is with `ClassName::class` and update `SproutForms_EntryModel` to the new class name as well.

**Comment by knynkwl** [comment]
@angrybrad Thanks, yeah I found it, it's `use barrelstrength\sproutforms\elements\Form;` then `Form::class` 🍻
