### ISSUE TITLE
No support for andRelatedTo in Entry Query

### ISSUE THREAD

**Issue by danbrellis** [craftcms/element-api#141]
### Description
It seems that an Entry query does not support the [new `andRelatedTo` param](https://github.com/craftcms/cms/issues/5733). Here is the var_dump of my criteria array:
```
array(3) {
  ["section"]=>
  string(15) "someSectionHandle"
  ["relatedTo"]=>
  int(784)
  ["andRelatedTo"]=>
  int(787)
}
```

When trying to run that, I get
```json
{
    "error": {
        "code": 404,
        "message": "Setting unknown property: craft\\elements\\db\\EntryQuery::andRelatedTo"
    }
}
```

I can confirm the same entry query does work on the frontend:

```twig
{% set entries = craft.entries()
  .section('someSectionHandle')
  .relatedTo(784])
  .andRelatedTo(787)
  .all() %}
```

### Steps to reproduce

Create an endpoint that uses the `craft\elements\Entry` elementType and set the criteria to an array with an `andRelatedTo` key:

```php
return [
  'endpoints' => [
    'api/enpoint.json' => function() {
      return [
        'elementType' => craft\elements\Entry::class,
        'criteria' => [
            'section' => 'someSectionHandle',
            'relatedTo' => 784,
            'andRelatedTo' => 787
        ],
        'transformer' => function(craft\elements\Entry $entry) {
          return ['title' => $entry->title];
        }
      ]
    }
  ]
];
```

### Additional info

- Craft version: 3.6.14
- PHP version: 7.4.5
- Plugins & versions: Element API (v2.7.0)

**Comment by darylknight** [comment]
Confirmed. Just ran into the same problem trying to do a multiple-relation filter using Sprig.

```
{% set queryParams =
	queryParams|merge({
		relatedTo: relatedParams,
		andRelatedTo: andRelatedParams
	})
%}

{% set entryQuery = craft.entries(queryParams) %}
```

![image](https://user-images.githubusercontent.com/1250017/121896533-1041cb80-cd2a-11eb-9a7d-43902687c9c6.png)

**Comment by danbrellis** [comment]
I dug into this a bit this morning and discovered it may be a result of how `andRelatedTo` is implemented in Craft. The issue seems to be that there is no `$andRelatedTo` property in the `craft\elements\db\EntryQuery` class (or its relevant parent, `craft\elements\db\ElementQuery`).

This seems to be important because there is no 'setter' when element-api tries to add the user-supplied criteria into the query in `element-api/src/resources/ElementResource.php` with `Craft::configure($query, $this->criteria);` (line 168).

I understand the reason for no `$andRelatedTo` property, `andRelatedTo()` is simply a helper function to format the value of `$relatedTo` but the result is that a setter never gets called and it's ultimately determined as a non-existent property.

I haven't found an Element-Api plugin-specific solution, but there is a CraftCMS solution: add 'andRelatedTo' into the switch statement in `craft\elements\db\ElementQuery`.

```php
public function __set($name, $value)
{
    switch ($name) {
        case 'site':
            $this->site($value);
            break;
        case 'localeEnabled':
            Craft::$app->getDeprecator()->log('ElementQuery::localeEnabled()', 'The `localeEnabled` element query param has been deprecated. `status()` should be used instead.');
            $this->enabledForSite = $value;
            break;
        case 'locale':
            Craft::$app->getDeprecator()->log('ElementQuery::locale()', 'The `locale` element query param has been deprecated. Use `site` or `siteId` instead.');
            $this->site($value);
            break;
        case 'order':
            Craft::$app->getDeprecator()->log('ElementQuery::order()', 'The `order` element query param has been deprecated. Use `orderBy` instead.');
            $this->orderBy = $value;
            break;
        case 'andRelatedTo':
            $this->andRelatedTo($value);
            break;
        default:
            parent::__set($name, $value);
    }
}
```

Not sure if this is an acceptable solution for the CraftCMS project and I haven't done any sort of exhaustive testing to see if this interferes with normal Element Query operations.

Would appreciate any guidance from the Element-Api or CraftCMS contributors.

Thanks!

**Comment by danbrellis** [comment]
Looks like you can tackle this in the Element-Api plugin in the getElementQuery() function.

in `src/resources/ElementResource.php`:
```php
protected function getElementQuery(): ElementQueryInterface
{
    /** @var string|ElementInterface $elementType */
    $elementType = $this->elementType;
    $query = $elementType::find();
    //Craft::configure($query, $this->criteria); //removed current line

    //added to handle 'andRelatedTo'
    foreach ($this->criteria as $name => $value) {
        if($name === 'andRelatedTo'){
            $query->andRelatedTo($value);
        }
        else $query->$name = $value;
    }

    return $query;
}
```

This isn't the most elegant way of handling this, but at least it's handled within the plugin if making changes to CraftCMS code isn't an option.

**Comment by brandonkelly** [comment]
There is no `$andRelatedTo` property on `craft\elements\db\ElementQuery`, and it wouldn’t really make sense to add a magic setter for it, because the whole point of `andRelatedTo()` is that it can be called multiple times, whereas `criteria` arrays can’t contain duplicate keys. So you’d only be able to set `andRelatedTo` at most once. Better to just define everything you need from the `relatedTo` param.
