### ISSUE TITLE
Preview and Cache causes draft to go 'live' immediately

### ISSUE THREAD

**Issue by Zae** [craftcms/element-api#143]
### Description
When using the `cache` parameter (which is now default, since 2.7.0), using preview in the CMS causes the API to always return the preview version.

I believe this is because element-api always caches the request and does not check if the request is a preview request. In subsequent requests the cache is found and simply returned.

In 2.6.0 the preview was broken, but because the published version kept being served instead of the draft, now with the changes in 2.7.0 the cache is cleared when a draft is saved which causes the draft to be cached.

### Steps to reproduce

1. Enable cache in element-api (default)
2. Supply the request with the correct X-Craft-Token
3. Element-api fills cache with current draft
4. Element-api serves cached draft version when requested without preview token

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version: MySQL 8.0.25
- Plugins & versions: 
   - Element-api: 2.7.0

**Comment by Zae** [comment]
I'm having some trouble validating if this actually works on our testing server right now, also according to brandon only checking for token is not correct, so maybe `isPreview` is correct, I just need to add the preview query param to the api request as well from my frontend to get it to work?

**Comment by Zae** [comment]
OK, I changed to start using`isPreview` again, people just need to remember to pass the `x-craft-live-preview` along.

Works correctly on our test server now :)

**Comment by brandonkelly** [comment]
Just released Element API 2.8.0, which no longer caches responses for Live Preview requests.
