### ISSUE TITLE
Events elementType returns Null even if there are events

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/element-api#155]
Im using the Verbb Events plugin and trying to return all events from the CMS using this code:

    

    use Craft;
    use verbb\events\elements\Event;
    use verbb\events\models\EventType;

    class Events {

        public static function index()
        {
            return [
                'elementType' => Event::class,
                'criteria' => [
                    'type'     => Craft::$app->request->getQueryParam('section') ? : 'event',
                    'offset'   => Craft::$app->request->getQueryParam('offset') ? : '0',
                ],
                'elementsPerPage' => Craft::$app->request->getQueryParam('items') ? : 10,
                'transformer' => function(Event $entry) {
                    return [
                        'title' => $entry->title,
                    ];
                },
            ];
        }
    }

However I get no entries back. If I run `$events = Event::find()->type($type)->all();` this does return information so wondering why the above doesn't work?

**Comment by brandonkelly** [comment]
The endpoint config should go in `config/element-api.php` using the format shown in this example: https://github.com/craftcms/element-api#setup

So something like:

```php
use verbb\events\elements\Event;
use verbb\events\models\EventType;

return [
    'endpoints' => [
        'events.json' => function() {
            return [
                'elementType' => Event::class,
                'criteria' => [
                    'type' => Craft::$app->request->getQueryParam('section') ?? 'event',
                    'offset' => Craft::$app->request->getQueryParam('offset') ?? 0,
                ],
                'elementsPerPage' => Craft::$app->request->getQueryParam('items') ?? 10,
                'transformer' => function(Event $event) {
                    return [
                        'title' => $event->title,
                    ];
                },
            ];
        },
    ],
];
```

**Comment by DowleyDeveloped** [comment]
Hi,

Apologies I the endpoint config set up and the above goes into another file:

`
<?php
    use config\endpoints\Collections;
    use config\endpoints\Events;

    return [
        'endpoints' => [
            'api/collections.json' => function() {
                return Collections::index();
            },
            'api/events.json' => function() {
                return Events::index();
            },
        ]
    ];

`

I've done this to keep the file clean. The collection endpoint gets entry data and works fine, however the Events does not

**Comment by brandonkelly** [comment]
Ah ok. And you’re sure that `$type` in your working code is getting set to `event` or whatever the `section` param is set to?

**Comment by DowleyDeveloped** [comment]
Yes, however even without I should be seeing something as the fallbacks all exist

**Comment by brandonkelly** [comment]
Try removing the `criteria` array, and see if it works without setting any event query params.
