### ISSUE TITLE
500 errors after upgrade to Craft  3.7.47.1 and plugin 2.8.6

### ISSUE THREAD

**Issue by joomkit** [craftcms/element-api#169]
### Description
UPgrade craft

### Steps to reproduce

1. Upgrade Craft from CLI
2. Call endpoint = 500 error

### Additional info

- Craft version: 3.7.47.1
- PHP version:7.4.2
- Database driver & version:
- Plugins & versions: element-api 2.8.6

**Comment by joomkit** [comment]
Closing this as it seems linked to a local Laravel valet issue

**Comment by jorisnoo** [comment]
I also experience this issue with the latest 2.8.6 update, unfortunately not only locally but on the server as well.

```
[error][craft\elementapi\controllers\DefaultController::actionIndex] Error resolving Element API endpoint: Setting unknown property: craft\elementapi\DataEvent::payload
2022-07-12 17:39:56 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\elementapi\DataEvent::payload in /vendor/yiisoft/yii2/base/BaseObject.php:163
```

**Comment by joomkit** [comment]
I closed it because it seems more related to my local dev environment running on Laravel valet.
I downgrade the plugin and composer and blitzed the vendor directory a couple of times but cant really say what specifically made it work, but I was having some issues after installing some other software. hth

**Comment by joomkit** [comment]
ps re open a new bug if need be :)

**Comment by iwe-hi** [comment]
@yingban Reopened it again in #170 .
