### ISSUE TITLE
`postDate` is not respected as cache TTL

### ISSUE THREAD

**Issue by michielroding** [craftcms/element-api#187]
### Description

When an Entry has a postDate in the future (pending) the `\craft\base\Element::@$enabledForSite` is disabled. 

Once the postDate is in the past this (and other fields) becomes enabled, but the API will still return the old disabled value. Adding a random cache-busting query parameter to the API call will return the correct new state.

We use Craft as a headless CMS and want to be able to schedule articles in the future. However the cache isn't expired when the postDate is in the past.

### Steps to reproduce

1. Create an Entry that will be published in the future
2. Request the Entry via the API with the criteria `status` set to `[Entry::STATUS_LIVE, Entry::STATUS_PENDING]`
4. Observe the `enabledForSite` state being false
5. Wait for the Entry to become public
6. Refetch the data via the API
7. The `enabledForSite` is still reported as false
8. Of course all other data is also stale; the status etc etc

### Additional info

- Craft version: 4.8.1
- PHP version: 8.1
- Database driver & version: mysql 5.7
- Plugins & versions: Element API 3.0.1.1

**Comment by brandonkelly** [comment]
Thanks for reporting that!

Just released Element API 4.1.0 with a fix for this. Now caches are no longer stored beyond the lowest expiry date from the results.

**Comment by brandonkelly** [comment]
Sorry, just realized you are talking about post dates, not expiry dates. I’ll have to think a bit more on that one, as we don’t currently have any code in place for restricting cache durations based on post date.
