### ISSUE TITLE
Ordering by Category and Title

### ISSUE THREAD

**Issue by jacksco** [craftcms/element-api#25]
Is it possible to output the JSON in order by Category (group) and Title? I've managed to find a way using the Group parameter but if I add 'order' => 'Title' it will no longer group by category.

`'criteria' => ['section' => 'stockistsListing', 'search' => 'stockistRegion:*', 'group' => 'stockistRegion.first().title'],`

**Comment by brandonkelly** [comment]
This is possible in v2 (for Craft 3 only), which lets you take complete control over fetching the data, etc., if you want to.
