### ISSUE TITLE
IP Whitelist

### ISSUE THREAD

**Issue by dGilli** [craftcms/element-api#32]
I am trying to restrict access to the API. Where do you think would be the best place to add a whitelisting?  Could it technically be possible to add the logic directly to the `elementapi.php` file?

**Comment by brandonkelly** [comment]
Yeah, you could do this by setting the endpoint to a function, and checking the IP at the beginning of the function:

```php
'my-endpoint.json' => function() {
    $ip = craft()->request->getIpAddress();
    if (!in_array($ip, ['1.2.3.4', '5.6.7.8'])) {
        throw new HttpException(403, 'Bad IP!');
    }

    return [
        // ...
    ];
},
```

Worth noting that it's pretty easy to spoof an IP address on a HTTP request, though.
