### ISSUE TITLE
Example for matrix field

### ISSUE THREAD

**Issue by buesing** [craftcms/element-api#34]
Could you set up a more elaborate example with matrix fields and asset retrieval? I have an entry with a matrix field that has multiple block types (images and text). I got it working so that I can already see the text but I can't get the assets. Just one working example would be a great help. Then I wouldn't have to go through the entire templating docs when I just want to use this plugin.

**Comment by brandonkelly** [comment]
Here’s an example of that: https://craftcms.stackexchange.com/a/13119/9
