### ISSUE TITLE
elementType: Purchasable

### ISSUE THREAD

**Issue by DrChills** [craftcms/element-api#35]
Hi, not sure what i'm doing wrong here!

Purchasable is a custom element type in craftcommerce ([ref](https://craftcommerce.com/docs/purchasables)), however I've tried multiple things and tey all error:

`'elementType' => 'purchasable',`
`'elementType' => 'Purchasable',`
`'elementType' => 'product',`

you see where I am going with this ;-)

I can retrieve Entry, Category etc just fine! 

any help would be much appreicated

**Comment by lukeholder** [comment]
`'elementType' => 'Commerce_Product',`
or
`'elementType' => 'Commerce_Variant',`
