### ISSUE TITLE
Elements creation

### ISSUE THREAD

**Issue by LouWii** [craftcms/element-api#37]
Hi there,

Thanks for creating that plugin, it's really handy in this world of web apps!

I have 2 questions regarding the future of this plugin. 
Are you planning to maintain it in the long term?
Are you planning to add a "write" feature ? (elements creation, user registration...)

Thanks and keep up the good work 👍

**Comment by takobell** [comment]
> Are you planning to maintain it in the long term?

Yes.

> Are you planning to add a "write" feature ? (elements creation, user registration...)

Probably not to this plugin.  The plan is to add a full read/write REST API to Craft itself.
