### ISSUE TITLE
Most elementTypes don't work

### ISSUE THREAD

**Issue by mofman** [craftcms/element-api#38]
Using V1 with Craft 2.6.2978 only a few elementtypes work, the rest gives me this message. 

> Argument 1 passed to Craft\ConfigService::Craft&#123;closure}() must be an instance of Craft\EntryModel, instance of Craft\AssetFileModel given

The ones that dont work include Asset, GlobalSet, MatrixBlock, User and my own Element Type, have you any suggestions?

Thanks

**Comment by takobell** [comment]
Can you share your `config/elementapi.php` file?

**Comment by brandonkelly** [comment]
Guessing you copied an example from the readme, and didn't change `EntryModel` to `AssetFileModel` in your `transformer` function’s signature.

**Comment by mofman** [comment]
Hi Brad

I'm just using the example provided on the v1 readme while testing and have
simply changed the elementType option to the ones I have listed.

Thanks

Andrew

**Comment by mofman** [comment]
Ah just realised my email didnt send last night, thanks Brandon will give this a go on monday, thanks!

**Comment by mofman** [comment]
Worked a treat brandon, thanks!

**Comment by brandonkelly** [comment]
Glad that worked!
