### ISSUE TITLE
Transformers includes?

### ISSUE THREAD

**Issue by qrazi** [craftcms/element-api#40]
Feature request: allow using includes, as described in the Fractal docs: http://fractal.thephpleague.com/transformers/ (heading "Including data")

**Comment by brandonkelly** [comment]
This is already possible, by supplying your own Transformer class. See the [`transformer`](https://github.com/craftcms/element-api#transformer) setting documentation for an example.

**Comment by qrazi** [comment]
I did not see what I meant in the documentation, or the source code. I am assuming this is coming from a bad explanation from me. I just created two PR's (#41 & #42), for each branch, adding support for this. In my Laravel projects I extensively use optionally inclusions, and sometimes exclusions. Both support nested inclusions. Doing this through `$defaultIncludes` is less flexible than allowing to configure which includes to use.

**Comment by brandonkelly** [comment]
Ah right, I overlooked the need to call `parseIncludes()` / `parseExcludes()` on the manager. Thanks for the PRs!
