### ISSUE TITLE
Feature Request: Minify output

### ISSUE THREAD

**Issue by katiasmet** [craftcms/element-api#44]
Hi guys

It seems like it isn't possible to minify the output from the API. Google pagespeed discovered the issue in my project's API. It could save 75% when compressions would be enabled.

Is this possible and if not can this be added to the next version :)? 

Thanks!

**Comment by takobell** [comment]
Any reason you couldn't just enable gzip output compression instead?

**Comment by brandonkelly** [comment]
Hey @katiasmet, each of the examples in the [readme](https://github.com/craftcms/element-api/blob/v1/README.md) set the `JSON_PRETTY_PRINT` flag in the `jsonOptions` endpoint setting for clarity, but if you don’t include that, then the output will be minified.

Once you’ve done that, it might not be a bad idea to enable gzip compression on your server as well, as @takobell suggested.

**Comment by katiasmet** [comment]
Hey @takobell and @brandonkelly 

Thanks for the fast answers :). It was indeed already minified but I forgot to add json to the htaccess.
