### ISSUE TITLE
Commerce Shipping Addresses

### ISSUE THREAD

**Issue by scottzirkel** [craftcms/element-api#45]
I'm trying to pull out the available shipping addresses for the current user during the checkout process. I can't seem to find the proper elementType to use.

I'm currently trying: `'elementType' => 'Commerce_AddressModel'` 

I'm getting an exception `No element type exists by the type “Commerce_AddressModel”.`

Is it possible to pull this in?

**Comment by takobell** [comment]
Check out `commerce/elementstypes` for the available element types in Commerce. There is one for Products, Variants and Orders. You'd want to probably use orders and work your way back to the address from there.

**Comment by scottzirkel** [comment]
Has the Order been created during checkout?

**Comment by takobell** [comment]
A "cart" is basically a row in the `commerce_orders` table with the `isCompleted` column set to `0`, so you should be able to query them during checkout.
