### ISSUE TITLE
Endpoints not working after craftcms update beta.21

### ISSUE THREAD

**Issue by S1lentium** [craftcms/element-api#51]
Endpoints not working after craftcms update beta.21
Returns:  404

**Comment by brandonkelly** [comment]
You will need to rename your Element API config file to `element-api.php` for it to work in Craft 3 Beta 20+. (see the note at the top of Beta 20’s [release notes](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta20---2017-07-07-critical).)

Also just added a note to the top of Element API 1.4.1’s [release notes](https://github.com/craftcms/element-api/blob/v2/CHANGELOG.md#241---2017-07-07) as well.
