### ISSUE TITLE
Feature request: querying by EntryRevisions

### ISSUE THREAD

**Issue by mattandrews** [craftcms/element-api#59]
I want to be able to request a specific revision (or a draft version) of an entry, in order to simulate a live preview feature for my site (a NodeJS app). Is this possible to do currently, or alternatively are there any plans to add this feature?

As far as I can tell, the [Entry Query Params](https://github.com/craftcms/docs/blob/master/en/entry-query-params.md) don't offer any parameters to query by revision/draft ID, and the [EntryRevisionsService](https://craftcms.com/classreference/services/EntryRevisionsService) isn't available alongside the Entry element type here.

**Comment by brandonkelly** [comment]
Duplicate of #43

**Comment by mattandrews** [comment]
Thanks! I did search for related issues but missed this one. Will follow #43.
