### ISSUE TITLE
Headers not cached

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/element-api#61]
Headers sent by the transformer are not cached when the `cache` option is enabled for an endpoint:

```
'cache' => true,
'criteria' => [
    'folderId' => $folder->id,
    'withTransforms' => ['galleryThumb', 'fullscreen']
],
'transformer' => function(AssetFileModel $image) {
    HeaderHelper::setHeader(['Access-Control-Allow-Origin' => '*']);
    // ...
}),
```

**Comment by linusschwab** [comment]
Any updates on this? @brandonkelly

We're having the problem that cached 404 requests return a 200 status code when served from the cache.

This would be solved if the headers were also cached, like this issue suggests. Alternatively it would maybe be possible to only cache the response for success status codes? There is even already an [open PR](https://github.com/craftcms/element-api/pull/133) that changes this.

**Comment by brandonkelly** [comment]
It’s not expected that you would set headers from the endpoint method, so I don’t think there’s any precedence to cache them.

If you want to set custom headers for Element API requests, you could do that via a custom, bootstrapped module:

```php
use craft\elementapi\controllers\DefaultController;
use yii\base\Event;

Event::on(
    DefaultController::class,
    DefaultController::EVENT_BEFORE_ACTION,
    function() {
        Craft::$app->response->headers->set('Access-Control-Allow-Origin', '*');
    }
);
```
