### ISSUE TITLE
JSON Feed example errors

### ISSUE THREAD

**Issue by vincentritter** [craftcms/element-api#63]
I've noticed that when using the JSON Feed example in the docs it throws an error:
"InvalidConfigException" -> 'Endpoint has an invalid elementType'.

This can be rectified by using:
```php
`'elementType' => craft\elements\Entry::class
```

and also using:
```php
`'transformer' => function(craft\elements\Entry $entry)
```

Craft Version: Craft CMS 3.0.0-beta.29
Element API Version: 2.4.3

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
