### ISSUE TITLE
install without composer

### ISSUE THREAD

**Issue by jnaklaas** [craftcms/element-api#65]
How do you install this plugin without composer? I looked into how to install composer but now I just want to smash my macbook and everything else within reach.

**Comment by brandonkelly** [comment]
Are you trying to install this for Craft 2 or 3? Only Craft 3’s version requires Composer, and that will chance once it’s out of beta. (You can view the Craft 2 installation instructions at https://github.com/craftcms/element-api/tree/v1.)
