### ISSUE TITLE
Color field return an empty object

### ISSUE THREAD

**Issue by SebastianoOlivo** [craftcms/element-api#67]
Hello, 

When I try to get the value of a color field I get back an empty Object : 

`entry => colorFieldName,`

Since this case is note documented, I have no idea if it's a bug or just the wrong way to get back the hexadecimal info of a color from a color field. 

Could you please check this ? 

Kr, 

Sebastiano

**Comment by brandonkelly** [comment]
Color fields will return a [craft\fields\data\ColorData](https://docs.craftcms.com/api/v3/craft-fields-data-colordata.html) object. You can either cast it to a string or call its `getHex()` function:

```php
'option1' => (string)$entry->colorField,
'option2' => $entry->colorField->getHex(),
```

**Comment by SebastianoOlivo** [comment]
Thanks for this clarification Brandon.
It work like a charm !
