### ISSUE TITLE
Plugin's call to JsonHelper::sendJsonHeaders() negates Cache-Control header config on endpoints

### ISSUE THREAD

**Issue by utugs** [craftcms/element-api#74]
While configuring my endpoints with Element API (V1 branch), I've come to find that I cannot set the Cache-Control header—other headers, yes, but specifically not Cache-Control. This looks to be the result of the Element API `ElementApiController` call to `JsonHelper::sendJsonHeaders` that ultimately overrides my endpoint config due to the fact that `JsonHelper::sendJsonHeaders` itself calls `HeaderHelper::setNoCache`.

Following Brandon's note in the following discussion, I also tried to set the Cache-Control header via a separate plugin to no avail.
https://craftcms.stackexchange.com/questions/14465/how-can-i-add-custom-headers-to-an-elementapi-response

**config/elementapi.php**
```php
<?php
namespace Craft;

return [
    'endpoints' => [
        'entries/<slug:{slug}>.json' => function($slug) {
            HeaderHelper::setHeader('Cache-Control: max-age: 3600, public');
            return [
                ...
            ];
        },
    ]
];
```
**Response Header**
```
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Date: Mon, 16 Apr 2018 19:24:42 GMT
Expires: Mon, 09 Apr 2018 19:24:42 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache
Transfer-Encoding: chunked
X-Powered-By: Craft CMS
```

Can you recommend a working solution (one that doesn't involve htaccess or other server-based configurations)?

**Comment by brandonkelly** [comment]
This has been fixed for the next Craft 2 release (coming out on Tuesday).
