### ISSUE TITLE
Redactor fields showing as an empty array

### ISSUE THREAD

**Issue by sanscheese** [craftcms/element-api#75]
Not sure if this is an issue for Redactor or the Element API.

When I create an endpoint (for a Global), if a field is a redactor field, it will appear in the JSON as an empty array. I change the field to Plain Text, the data will display properly.

**Comment by brandonkelly** [comment]
You probably just need to typecast the value to a string:

```php
'body' => (string)$entry->body,
```

**Comment by sanscheese** [comment]
This is occurring when using the default transformer. If I do a simple transformer to target just this field, it then the value correctly in the JSON (even without the need to typecast):

`'transformer' => function(Entry $entry) {
    return [
        'summary' => $entry->summary,
    ];
},`

**Comment by brandonkelly** [comment]
Ah gotcha, thanks for the clarification.

**Comment by sanscheese** [comment]
And, I think this may be just for Globals.

**Comment by brandonkelly** [comment]
Alright, this is fixed for the next release. You can get the fix now by changing your `craftcms/element-api` version constraint in composer.json to `"dev-v2 as 2.5.4"`, and then running `composer update`.

**Comment by sanscheese** [comment]
Thanks Brandon. Love your work 😄

**Comment by brandonkelly** [comment]
Element API 2.6.0 is out now with this fix.
