### ISSUE TITLE
Cache does not store current site in the cache key

### ISSUE THREAD

**Issue by croxton** [craftcms/element-api#76]
Calling the same endpoint from different site domains yields the same cached json. I assume therefore that the current `CRAFT_SITE` is not included in the cache key?

**Comment by angrybrad** [comment]
@MakeilaLundy @Radabaugh Cache key is generated [here](https://github.com/craftcms/element-api/blob/v2/src/controllers/DefaultController.php#L90). It should probably be site-aware.

**Comment by folkrav** [comment]
Any updates on this? I've got a big endpoint that I managed to bring down from ~12s to ~3s (local dev environment, faster in staging...), but that would benefit greatly from caching (could go down to ~30ms with it turned on), but I can't use it right now because it's a multilingual site.

Should I make a PR?

**Comment by Radabaugh** [comment]
It should be fixed with this pull request #77

**Comment by folkrav** [comment]
Excellent! Thanks a lot for the quick response.

**Comment by folkrav** [comment]
Happy to see this has been merged! Seems like releases were almost monthly up to last December, then it stopped. I guess it had to do with the last stretch of work before Craft 3's release. I was simply wondering if there a planned release including this fix in the foreseeable future, or is it still too soon to think about it?

Just to know if I should be looking at an alternative solution for the time being - deadlines are approaching for the project I mentioned in my other comment.

**Comment by angrybrad** [comment]
Just released 2.5.3 with this change: https://github.com/craftcms/element-api/releases/tag/2.5.3
