### ISSUE TITLE
Caching transformed image urls

### ISSUE THREAD

**Issue by keithmancuso** [craftcms/element-api#81]
Running into a strange case that im not sure how to handle. We have caching turned on and some of the endpoints include transformed images. The issue is that its caching the "tranform" url which seems to redo the transform on every page load vs just replacing the url with the existing image.

I may be getting this wrong but any advice?

**Comment by brandonkelly** [comment]
We just released v2.5.4 which resolves this by always forcing image transforms to be generated immediately, rather than returning a transform generation URL in the API response.

You will need to clear your data caches if any of your endpoints are still affected by this issue.
