### ISSUE TITLE
Accessing api from a localized url gives Template Not Found error.

### ISSUE THREAD

**Issue by a-am** [craftcms/element-api#86]
We have several endpoints:  `'api/livecontent.json' => [`  when we try to access this through `example.com/es/api/livecontent.json` the system gives a Page Not Found Template Not Found error.  If we access through the default site not the secondary localized site it works fine. Does a separate element-api.php config file need to be setup for the second locale?

**Comment by khushbuyeole** [comment]
I am facing same problem...
Any suggestions??

**Comment by brandonkelly** [comment]
Just tested this locally and it’s working as expected. Let me know if you’re still needing help with this.
