### ISSUE TITLE
Does Element API support per environment configuration?

### ISSUE THREAD

**Issue by chrislam** [craftcms/element-api#95]
As per the description, am I able to set `cache => false` for dev and `cache => true` for other environments? If so, so I use the same system as other Craft config files to do this?

**Comment by EternalBlack** [comment]
@chrislam I don't know if you could use the same system as other Craft config files do but I currently use `'cache' => (bool)getenv('USECACHE'),` with `USECACHE=1`. Works fine for me.

**Comment by brandonkelly** [comment]
Yep, all plugin config files support [multi-environment configuration](https://docs.craftcms.com/v3/config/environments.html#multi-environment-configs).

```php
return [
    '*' => [
        // all your endpoint configs
    ],
    'production' => [
        'defaults' => [
            'cache' => true,
        ],
    ]
];
```

Or as @EternalBlack pointed out, you could just refer to an environment variable with `getenv()`.

**Comment by chrislam** [comment]
Cool, thanks for the response :)
